# for new versions of the arduino ide, change board_tag to nano

USER_LIB_PATH = .
BOARD_TAG   = nano328
ARDUINO_DIR = /usr/share/arduino
ARDUINO_LIBS = Wire SPI Adafruit-GFX Adafruit_SSD1306

include /usr/share/arduino/Arduino.mk
